/* ATUALIZA NOTA FISCAL */

CREATE VIEW V_NOTA_FISCAL AS
SELECT 
	ID_NOTA_FISCAL AS ID_NOTA_FISCAL, 
	SUM(TOTAL) 	   AS SOMA
FROM ITEM_NOTA 		AS ITEM_NOTA
GROUP BY ID_NOTA_FISCAL
GO

SELECT * FROM V_NOTA_FISCAL
WHERE ID_NOTA_FISCAL = 1000 
GO

CREATE VIEW V_CARGA_NF AS
SELECT 
	IDNOTA  		   AS IDNOTA, 
	NOTA_FISCAL.TOTAL  AS TOTALNOTA, 
	V_NOTA_FISCAL.SOMA AS SOMA
FROM NOTA_FISCAL 		 AS NOTA_FISCAL
INNER JOIN V_NOTA_FISCAL AS V_NOTA_FISCAL
ON IDNOTA = ID_NOTA_FISCAL
GO

SELECT * FROM V_CARGA_NF
GO

UPDATE V_CARGA_NF SET TOTALNOTA = SOMA
GO

/* REALIZANDO CONSULTA NO AMBIENTE OLTP */

SELECT 
	CLIENTE.NOME		AS NOME, 
	CLIENTE.SOBRENOME   AS "CLIENTE", 
	CLIENTE.SEXO  		AS SEXO, 
	NOTA_FISCAL.DATA 	AS DATA, 
	NOTA_FISCAL.IDNOTA 	AS IDNOTA, 
	PRODUTO.PRODUTO     AS PRODUTO, 
	NOTA_FISCAL.TOTAL   AS TOTAL
FROM CLIENTE AS CLIENTE
INNER JOIN NOTA_FISCAL  AS NOTA_FISCAL
ON CLIENTE.IDCLIENTE = NOTA_FISCAL.ID_CLIENTE
INNER JOIN ITEM_NOTA 	AS ITEM_NOTA
ON NOTA_FISCAL.IDNOTA = ITEM_NOTA.ID_NOTA_FISCAL
INNER JOIN PRODUTO 		AS PRODUTO
ON PRODUTO.IDPRODUTO = ITEM_NOTA.ID_PRODUTO
ORDER BY 5
GO