
SELECT 
	NOME, 
	IDNOTA, 
	DATA, 
	IDITEMNOTA, 
	PRODUTO, 
	VALOR, 
	QUANTIDADE, 
	NOTA_FISCAL.TOTAL
FROM CLIENTE 			AS CLIENTE
INNER JOIN NOTA_FISCAL  AS NOTA_FISCAL
ON IDCLIENTE = ID_CLIENTE
INNER JOIN ITEM_NOTA 	AS ITEM_NOTA
ON ID_NOTA_FISCAL = IDNOTA
INNER JOIN PRODUTO 		AS PRODUTO
ON IDPRODUTO = ID_PRODUTO
ORDER BY 2
GO

SELECT * FROM ITEM_NOTA 

SELECT * FROM NOTA_FISCAL