USE COMERCIO_OLTP
GO

DROP VIEW RELATORIO_VENDAS
GO

CREATE VIEW RELATORIO_VENDAS AS
SELECT CLIENTE.IDCLIENTE 												AS IDCLIENTE,
	   VENDEDOR.IDVENDEDOR 												AS IDVENDEDOR,
	   PRODUTO.IDPRODUTO 												AS IDPRODUTO,
	   FORNECEDOR.IDFORNECEDOR  										AS IDFORNECEDOR,
	   NOTA_FISCAL.IDNOTA 												AS IDNOTA,
	   IDFORMA 															AS IDFORMA,
	   ITEM_NOTA.QUANTIDADE 											AS QUANTIDADE,
	   (ITEM_NOTA.QUANTIDADE * PRODUTO.CUSTO_MEDIO) 					AS CUSTO_TOTAL,
	   (ITEM_NOTA.TOTAL - (ITEM_NOTA.QUANTIDADE * PRODUTO.CUSTO_MEDIO)) AS LUCRO_TOTAL,
	   ITEM_NOTA.TOTAL  												AS TOTAL_ITEM,
	   NOTA_FISCAL.DATA 												AS DATA
FROM NOTA_FISCAL 			AS NOTA_FISCAL 
INNER JOIN ITEM_NOTA 		AS ITEM_NOTA 		ON ( NOTA_FISCAL.IDNOTA = ITEM_NOTA.ID_NOTA_FISCAL )
INNER JOIN CLIENTE 			AS CLIENTE 	 		ON ( CLIENTE.IDCLIENTE = NOTA_FISCAL.ID_CLIENTE )
INNER JOIN VENDEDOR 		AS VENDEDOR  		ON ( VENDEDOR.IDVENDEDOR = NOTA_FISCAL.ID_VENDEDOR )
INNER JOIN PRODUTO 			AS PRODUTO 	 		ON ( PRODUTO.IDPRODUTO = ID_PRODUTO )
INNER JOIN FORMA_PAGAMENTO  AS FORMA_PAGAMENTO  ON ( FORMA_PAGAMENTO.IDFORMA = NOTA_FISCAL.ID_FORMA )
INNER JOIN FORNECEDOR 		AS FORNECEDOR 		ON (FORNECEDOR.IDFORNECEDOR = PRODUTO.ID_FORNECEDOR) 
GO

SELECT * FROM RELATORIO_VENDAS
ORDER BY IDNOTA
GO

