		------------------------
		---CONEXAO COM O DW-----
		------------------------

		USE COMERCIO_DW
		GO

		------------------------
		--CRIAÇAO DA PROCEDURE--
		------------------------

		CREATE PROC CARGA_FATO
		AS

		DECLARE @FINAL DATETIME 
		DECLARE	@INICIAL DATETIME
		
		SELECT  @FINAL = MAX(DATA)
		FROM COMERCIO_DW.DBO.DIM_TEMPO 		AS DIM_TEMPO

		SELECT @INICIAL = MAX(DATA)
			FROM COMERCIO_DW.DBO.FATO 		AS FATO
			JOIN COMERCIO_DW.DBO.DIM_TEMPO  AS DIM_TEMPO ON (FATO.IDTEMPO = DIM_TEMPO.IDSK)

		IF @INICIAL IS NULL
		BEGIN
			SELECT @INICIAL = MIN(DATA)
			FROM COMERCIO_DW.DBO.DIM_TEMPO 	AS DIM_TEMPO
		END

		INSERT INTO COMERCIO_DW.DBO.FATO(
			IDNOTA,
			IDCLIENTE,
			IDVENDEDOR,
			IDFORMA,
			IDFORNECEDOR,
			IDPRODUTO,
			IDTEMPO,
			QUANTIDADE,
			TOTAL_ITEM,
			CUSTO_TOTAL,
			LUCRO_TOTAL )
		SELECT
			NOTA_FISCAL.IDSK AS IDNOTA,
			DIM_CLIENTE.IDSK AS IDCLIENTE,
			DIM_VENDEDOR.IDSK AS IDVENDEDOR,
		    DIM_FORMA.IDSK AS IDFORMA,
		    DIM_FORNECEDOR.IDSK AS IDFORNECEDOR,
			DIM_PRODUTO.IDSK AS IDPRODUTO,	
			T.IDSK AS IDTEMPO,
			ST_FATO.QUANTIDADE,
			ST_FATO.TOTAL_ITEM,
			ST_FATO.CUSTO_TOTAL,
			ST_FATO.LUCRO_TOTAL
	
		FROM
			COMERCIO_STAGE.DBO.ST_FATO ST_FATO

			INNER JOIN DBO.DIM_FORMA 		  AS DIM_FORMA
			on (ST_FATO.IDFORMA=DIM_FORMA.IDFORMA)	 

			INNER JOIN DBO.DIM_NOTA 		  AS DIM_NOTA
			on (ST_FATO.IDNOTA=NOTA_FISCAL.IDNOTA)

				INNER JOIN DBO.DIM_FORNECEDOR AS DIM_FORNECEDOR
			on (ST_FATO.IDFORNECEDOR=FNOTA_FISCAL.IDFORNECEDOR
				AND (NOTA_FISCAL.INICIO <= ST_FATO.DATA AND (NOTA_FISCAL.FIM >= ST_FATO.DATA) or (NOTA_FISCAL.FIM IS NULL)))

			INNER JOIN DBO.DIM_CLIENTE 		  AS DIM_CLIENTE
			on (ST_FATO.IDCLIENTE=DIM_CLIENTE.IDCLIENTE
				AND (DIM_CLIENTE.INICIO <= ST_FATO.DATA
				AND (DIM_CLIENTE.FIM >= ST_FATO.DATA) or (DIM_CLIENTE.FIM IS NULL)))

				INNER JOIN DBO.DIM_VENDEDOR   AS DIM_VENDEDOR
			on (ST_FATO.IDVENDEDOR=DIM_VENDEDOR.IDVENDEDOR
				AND (DIM_VENDEDOR.INICIO <= ST_FATO.DATA
				AND (DIM_VENDEDOR.FIM >= ST_FATO.DATA) or (DIM_VENDEDOR.FIM IS NULL)))

				INNER JOIN DBO.DIM_PRODUTO    AS DIM_PRODUTO
			ON (ST_FATO.IDPRODUTO=DIM_DIM_PRODUTO.IDPRODUTO 
			AND (DIM_DIM_PRODUTO.INICIO <= ST_FATO.DATA 
			AND (DIM_DIM_PRODUTO.FIM >= ST_FATO.DATA) OR (DIM_PRODUTO.FIM IS NULL)))

			INNER JOIN DBO.DIM_TEMPO 		  AS DIM_TEMPO
			ON (CONVERT(VARCHAR, DIM_TEMPO.DATA,102) = CONVERT(VARCHAR,
			ST_FATO.DATA,102))
			WHERE ST_FATO.DATA > @INICIAL AND ST_FATO.DATA < @FINAL
			--WHERE ST_FATO.DATA BETWEEN @INICIAL AND @FINAL
GO










