USE [COMERCIO_DW]
GO

CREATE VIEW V_ANALISE_FORNECEDOR AS
SELECT 
	NOTA_FISCAL.NOME    AS FORNECEDOR,
	DIM_TEMPO.ANO       AS ANO,
SUM(ST_FATO.QUANTIDADE) AS QUANTIDADE,
SUM(ST_FATO.TOTAL_ITEM) AS TOTAL_VENDIDO

FROM COMERCIO_STAGE.DBO.ST_FATO AS  ST_FATO

INNER JOIN DBO.DIM_FORNECEDOR   AS DIM_FORNECEDOR
ON ST_FATO.IDFORNECEDOR = NOTA_FISCAL.IDFORNECEDOR

INNER JOIN DBO.DIM_TEMPO        AS DIM_TEMPO
ON (CONVERT(VARCHAR, DIM_TEMPO.DATA, 102) =
CONVERT(VARCHAR, ST_FATO.DATA, 102))

GROUP BY NOTA_FISCAL.NOME, DIM_TEMPO.ANO
GO

SELECT 
	DISTINCT 
	DIM_TEMPO.ANO
FROM DIM_TEMPO 
INNER JOIN FATO AS FATO ON DIM_TEMPO.IDSK = FATO.IDTEMPO

SELECT  
	FORNECEDOR, 
	ANO, 
	QUANTIDADE, 
	TOTAL_VENDIDO
FROM V_ANALISE_FORNECEDOR
WHERE (ANO = @ANO)
ORDER BY FORNECEDOR

SELECT        
	FORNECEDOR, 
	ANO, 
	QUANTIDADE, 
	TOTAL_VENDIDO
FROM V_ANALISE_FORNECEDOR
WHERE ANO IN ( @ANO )
ORDER BY FORNECEDOR



SELECT 
	DISTINCT 
	PRODUTO.NOME 	AS PRODUTO,
	CATEGORIA.NOME  AS CATEGORIA
FROM DIM_PRODUTO 			AS DIM_PRODUTO
INNER JOIN FATO  			AS FATO
ON PRODUTO.IDSK = FATO.IDPRODUTO
INNER JOIN DIM_FORNECEDOR 	AS DIM_FORNECEDOR
ON DIM_FORNECEDOR.IDSK = FATO.IDFORNECEDOR
INNER JOIN CATEGORIA 		AS CATEGORIA
ON IDCATEGORIA = ID_CATEGORIA
WHERE DIM_FORNECEDOR.NOME = @FORNECEDOR